### PR TITLE
Edit post pc

### PR DESCRIPTION
**Pull request by gpavan19**
Closes # 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] I have selected a committee co-chair to review the PR

### CODE REVIEW

**Review by scontento — APPROVED** [review]
review

**Comment by JohnMoehrke** [comment]
Luke will redline review on Monday on master

**Comment by JohnMoehrke** [comment]
Committee Discussion: Might we use another round of Public Comment? The level of changes and little bit of review would argue for the benefit of Public Comment. There are known changes coming on the subscription backport. 
Being Public Comment would prevent it from being qualified for EU connectathon. 
Plan to promote this as TI, with strong messaging we are looking for feedback and critical review.
Will watch this work item closely. Will revoke TI if we get strong comments against.

**Comment by JohnMoehrke** [comment]
Motion to approve for TI
Moved: Gianluca
Second: Luke
Vote: 7-0-0

**Pull request merged**
